apiVersion: v1
kind: Pod
metadata: 
  name: red
  labels:
    name: red
    app: red
spec:
  containers:
  - name: red
    image: kodekloud/webapp-color
    ports:
    - containerPort: 8080
    env:
    - name: APP_COLOR
      value: red
