apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: red
  name: red
spec:
  ports:
  - name: 80-8080
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: red
  type: NodePort
status:
  loadBalancer: {}
