apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: green
  name: green
spec:
  ports:
  - name: 80-8080
    nodePort: 30081
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: green
  type: NodePort
status:
  loadBalancer: {}
