apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: blue
  name: blue
spec:
  ports:
  - name: 80-8080
    nodePort: 30082
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: blue
  type: NodePort
status:
  loadBalancer: {}
